---
role_name_check: 1
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ansible-debian12-test
    image: tmolnar-debian:latest
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  options:
    managed: False
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
